## 붓꽃의 품종 분류
setosa, versicolor, virginica 종으로 분류한 붓꽃의 측정 데이터 <br>
분류(Classification) 문제에 해당하고, 출력될 수 있는 값(붓꽃의 종류)들을 클래스(Class)라고 한다. <br>
특정 데이터 포인트에 대한 출력, 즉 품종을 레이블(Label)이라고 한다.

### 데이터 적재
데이터는 scikit-learn의 datasets 모듈에 포함되어 있다. <br>
load_iris 함수를 사용하여 데이터를 적재

In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
print('iris_dataset의 키: \n', iris_dataset.keys())

iris_dataset의 키: 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
type(iris_dataset)

sklearn.utils.Bunch

In [4]:
print('타깃의 이름: ', iris_dataset['target_names'])

타깃의 이름:  ['setosa' 'versicolor' 'virginica']


In [5]:
print('특성 이름: ', iris_dataset['feature_names'])

특성 이름:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print('데이터 타입: ', type(iris_dataset['data']))

데이터 타입:  <class 'numpy.ndarray'>


In [7]:
print('데이터의 처음 다섯 행:\n', iris_dataset['data'][:5])

데이터의 처음 다섯 행:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [8]:
print('target의 타입:\n', type(iris_dataset['target']))

target의 타입:
 <class 'numpy.ndarray'>


In [9]:
print('타깃:\n', iris_dataset['target'])

타깃:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### 성과 측정: 훈련 데이터와 테스트 데이터
모델이 데이터를 기억한다는 것은 모델을 잘 일반화하지 않았다는 뜻이다. <br>
머신러닝 모델을 만들 때 사용하는 데이터: 훈련 데이터 혹은 훈련 세트(training set) <br>
머신러닝 모델이 얼마나 잘 작동하는지 측정하는 데 사용하는 데이터: 테스트 데이터, 테스트 세트(test set) 혹은 홀드아웃 세트(hold-out set) <br>
scikit-learn은 데이터셋을 섞어서 나눠주는 train_test_split 함수 제공

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=0)

In [11]:
print('X_train 크기: ', X_train.shape)
print('y_train 크기: ', y_train.shape)

X_train 크기:  (112, 4)
y_train 크기:  (112,)
