# Class

In [3]:
# class 예시
class Man:
    def __init__(self, name):    # init: class reset
        self.name = name    # 인스턴스 변수 초기화
        print("Initialized!")
    
    def hello(self):
        print("Hello " + self.name + "!")
        
    def goodbye(self):
        print("Bye " + self.name + "!")
        
m = Man("Jin")
m.hello()
m.goodbye()

Initialized!
Hello Jin!
Bye Jin!


## Numpy

In [3]:
import numpy as np

In [6]:
# creat numpy array - np.array
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [9]:
# numpy Arithmetic operation
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)   #원소별 계산
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [12]:
x = np.array([1.0, 2.0, 3.0])
x / 0.5

array([2., 4., 6.])

In [15]:
# 다차원 배열
A = np.array([[1, 2], [3, 4]])    #인자 안에 인자들
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


In [17]:
# 다차원 배열의 연산
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])
print(A + B)
print(A * B)

[[3 5]
 [7 9]]
[[ 2  6]
 [12 20]]
