# Class

In [3]:
# class 예시
class Man:
    def __init__(self, name):    # init: class reset
        self.name = name    # 인스턴스 변수 초기화
        print("Initialized!")
    
    def hello(self):
        print("Hello " + self.name + "!")
        
    def goodbye(self):
        print("Bye " + self.name + "!")
        
m = Man("Jin")
m.hello()
m.goodbye()

Initialized!
Hello Jin!
Bye Jin!


## Numpy

In [3]:
import numpy as np

In [6]:
# creat numpy array - np.array
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [9]:
# numpy Arithmetic operation
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)   #원소별 계산
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [12]:
x = np.array([1.0, 2.0, 3.0])
x / 0.5

array([2., 4., 6.])

In [15]:
# 다차원 배열
A = np.array([[1, 2], [3, 4]])    #인자 안에 인자들
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64


In [17]:
# 다차원 배열의 연산
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])
print(A + B)
print(A * B)

[[3 5]
 [7 9]]
[[ 2  6]
 [12 20]]


## 브로드캐스트

In [20]:
# 1차원 배열인 B가 2차원 배열인 A에 맞추어 확장되어 연신
A = np.array([[1, 2], [3, 4]])
B = np.array([10 , 20])
A * B

array([[10, 40],
       [30, 80]])

### 원소 접근

In [28]:
# 원소 접근법
X = np.array([[10, 15], [2, 4], [23, 54]])
print(X)
print("_____")
print(X[0])    # 행
print(X[0], [1])    # (0,1)자리의 원소
print("_____")
for row in X:   # for 문으로도 접근 가능
    print(row)
print("_____")
X = X.flatten()    # 평단화
print(X)
print("_____")
print(X[np.array([0, 2, 4])])
print("_____")

# 조건에 맞는 원소
print(X > 15)
print("_____")
print(X[X>15])   # 참인 값의 인덱스

[[10 15]
 [ 2  4]
 [23 54]]
_____
[10 15]
[10 15] [1]
_____
[10 15]
[2 4]
[23 54]
_____
[10 15  2  4 23 54]
_____
[10  2 23]
_____
[False False False False  True  True]
_____
[23 54]
